# Generated by Django 4.1.3 on 2023-01-27 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAffectedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pap_image', models.ImageField(blank=True, upload_to='pap_uploads')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=128)),
                ('nin', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.PositiveIntegerField(blank=True, default=0)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_list_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('tree_image', models.ImageField(blank=True, upload_to='tree_uploads')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_trees', to='api.treelist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_trees', to='api.projectaffectedperson')),
            ],
        ),
        migrations.CreateModel(
            name='TenureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tenures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_list_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_image', models.ImageField(blank=True, upload_to='land_uploads')),
                ('survey_no', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('size', models.FloatField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('land_use', models.TextField(blank=True)),
                ('land_services', models.TextField(blank=True)),
                ('rate', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('land_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_land', to='api.landlist')),
                ('pap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_lands', to='api.projectaffectedperson')),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenure_types', to='api.tenuretype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.PositiveIntegerField()),
                ('district', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_list_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_image', models.ImageField(blank=True, upload_to='crop_uploads')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('quality', models.CharField(choices=[('Mature_good', 'Mature_good'), ('Mature', 'Mature'), ('Immature_good', 'Immature_good'), ('Immature', 'Immature')], max_length=20)),
                ('rate', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('crop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_list', to='api.croplist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('pap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_crops', to='api.projectaffectedperson')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_list_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_image', models.ImageField(blank=True, upload_to='construction_uploads')),
                ('size', models.FloatField(default=0)),
                ('number_of_construction', models.PositiveSmallIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_construction', to='api.constructionlist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_construction', to='api.projectaffectedperson')),
            ],
        ),
    ]
